name: AFKZone
main: Luthfi\AFKZone\Main
version: 1.0.1
api: [5.0.0]
depend: [EconomyAPI]
commands:
  afkzone:
    description: Configure the AFK zone
    usage: /afkzone <setworld|setposition>
    aliases: [az]
    permission: afkzone.command
  settopafk:
    description: Allow to set leaderboard
    permission: afkzone.settopafk
permissions:
  afkzone.command:
    description: Allows the player to configure the AFKZone
    default: op
  afkzone.settopafk:
    description: Allows the player to configure the AFKZone Leaderboard
    default: op
